{
 "title": "Nodes View Basic",
 "description": "This is a modern 'Nodes View' dashboard for your Kubernetes cluster(s). Made for kube-prometheus-stack and take advantage of the latest Grafana features. GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info, node)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_uname_info{nodename=~\"(?i:($node))\"},instance)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "Node Name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_node_info{node=\"$node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "OS Image",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_node_info{node=\"$node\"}",
     "legendFormat": "{{os_image}}"
    }
   ]
  },
  {
   "title": "Node Private IP",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_node_info{node=\"$node\"}",
     "legendFormat": "{{internal_ip}}"
    }
   ]
  },
  {
   "title": "List of pods on node",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "kube_pod_info{node=\"$node\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Pods on node",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{node=\"$node\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "CPU (5m)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(node) (irate(node_cpu_seconds_total{node=\"$node\", mode!=\"idle\"}[5m])) / on(node) group_left sum by (node)((irate(node_cpu_seconds_total{node=\"$node\"}[5m])))) * 100"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{node=\"$node\"} - node_memory_MemAvailable_bytes{node=\"$node\"}) / sum(node_memory_MemTotal_bytes{node=\"$node\"})"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{node=\"$node\"} - node_boot_time_seconds{node=\"$node\"}"
    }
   ]
  }
 ]
}